// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sample_neighbor_pairs_cpp
IntegerMatrix sample_neighbor_pairs_cpp(IntegerMatrix nbrs, NumericMatrix knn_distances, int n_neighbors);
RcppExport SEXP _pacmapr_sample_neighbor_pairs_cpp(SEXP nbrsSEXP, SEXP knn_distancesSEXP, SEXP n_neighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type nbrs(nbrsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type knn_distances(knn_distancesSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_neighbor_pairs_cpp(nbrs, knn_distances, n_neighbors));
    return rcpp_result_gen;
END_RCPP
}
// sample_mn_pairs_cpp
IntegerMatrix sample_mn_pairs_cpp(NumericMatrix X, int n_MN, int distance_kind, Nullable<int> random_state);
RcppExport SEXP _pacmapr_sample_mn_pairs_cpp(SEXP XSEXP, SEXP n_MNSEXP, SEXP distance_kindSEXP, SEXP random_stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_MN(n_MNSEXP);
    Rcpp::traits::input_parameter< int >::type distance_kind(distance_kindSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type random_state(random_stateSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_mn_pairs_cpp(X, n_MN, distance_kind, random_state));
    return rcpp_result_gen;
END_RCPP
}
// sample_fp_pairs_cpp
IntegerMatrix sample_fp_pairs_cpp(IntegerMatrix pair_neighbors, int n_points, int n_neighbors, int n_FP, Nullable<int> random_state);
RcppExport SEXP _pacmapr_sample_fp_pairs_cpp(SEXP pair_neighborsSEXP, SEXP n_pointsSEXP, SEXP n_neighborsSEXP, SEXP n_FPSEXP, SEXP random_stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type pair_neighbors(pair_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_points(n_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_FP(n_FPSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type random_state(random_stateSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_fp_pairs_cpp(pair_neighbors, n_points, n_neighbors, n_FP, random_state));
    return rcpp_result_gen;
END_RCPP
}
// pacmap_optimize_cpp
List pacmap_optimize_cpp(NumericMatrix Y_init, IntegerMatrix pair_nb, IntegerMatrix pair_MN, IntegerMatrix pair_FP, double lr, IntegerVector num_iters, int n_threads, bool verbose);
RcppExport SEXP _pacmapr_pacmap_optimize_cpp(SEXP Y_initSEXP, SEXP pair_nbSEXP, SEXP pair_MNSEXP, SEXP pair_FPSEXP, SEXP lrSEXP, SEXP num_itersSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y_init(Y_initSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pair_nb(pair_nbSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pair_MN(pair_MNSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pair_FP(pair_FPSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type num_iters(num_itersSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(pacmap_optimize_cpp(Y_init, pair_nb, pair_MN, pair_FP, lr, num_iters, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sample_fp_pairs_nearby_cpp
IntegerMatrix sample_fp_pairs_nearby_cpp(NumericMatrix Y, IntegerMatrix pair_neighbors, IntegerMatrix old_pair_FP, double low_dist_thres, Nullable<int> random_state);
RcppExport SEXP _pacmapr_sample_fp_pairs_nearby_cpp(SEXP YSEXP, SEXP pair_neighborsSEXP, SEXP old_pair_FPSEXP, SEXP low_dist_thresSEXP, SEXP random_stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pair_neighbors(pair_neighborsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type old_pair_FP(old_pair_FPSEXP);
    Rcpp::traits::input_parameter< double >::type low_dist_thres(low_dist_thresSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type random_state(random_stateSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_fp_pairs_nearby_cpp(Y, pair_neighbors, old_pair_FP, low_dist_thres, random_state));
    return rcpp_result_gen;
END_RCPP
}
// localmap_optimize_cpp
List localmap_optimize_cpp(NumericMatrix Y_init, IntegerMatrix pair_nb, IntegerMatrix pair_MN, IntegerMatrix pair_FP, double lr, IntegerVector num_iters, double low_dist_thres, int n_threads, Nullable<int> random_state, bool verbose);
RcppExport SEXP _pacmapr_localmap_optimize_cpp(SEXP Y_initSEXP, SEXP pair_nbSEXP, SEXP pair_MNSEXP, SEXP pair_FPSEXP, SEXP lrSEXP, SEXP num_itersSEXP, SEXP low_dist_thresSEXP, SEXP n_threadsSEXP, SEXP random_stateSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y_init(Y_initSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pair_nb(pair_nbSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pair_MN(pair_MNSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pair_FP(pair_FPSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type num_iters(num_itersSEXP);
    Rcpp::traits::input_parameter< double >::type low_dist_thres(low_dist_thresSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type random_state(random_stateSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(localmap_optimize_cpp(Y_init, pair_nb, pair_MN, pair_FP, lr, num_iters, low_dist_thres, n_threads, random_state, verbose));
    return rcpp_result_gen;
END_RCPP
}
// pacmap_fit_optimize_cpp
List pacmap_fit_optimize_cpp(NumericMatrix Y_init, IntegerMatrix pair_XP, int n_basis, double lr, IntegerVector num_iters, int n_threads, bool verbose);
RcppExport SEXP _pacmapr_pacmap_fit_optimize_cpp(SEXP Y_initSEXP, SEXP pair_XPSEXP, SEXP n_basisSEXP, SEXP lrSEXP, SEXP num_itersSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y_init(Y_initSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pair_XP(pair_XPSEXP);
    Rcpp::traits::input_parameter< int >::type n_basis(n_basisSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type num_iters(num_itersSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(pacmap_fit_optimize_cpp(Y_init, pair_XP, n_basis, lr, num_iters, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pacmapr_sample_neighbor_pairs_cpp", (DL_FUNC) &_pacmapr_sample_neighbor_pairs_cpp, 3},
    {"_pacmapr_sample_mn_pairs_cpp", (DL_FUNC) &_pacmapr_sample_mn_pairs_cpp, 4},
    {"_pacmapr_sample_fp_pairs_cpp", (DL_FUNC) &_pacmapr_sample_fp_pairs_cpp, 5},
    {"_pacmapr_pacmap_optimize_cpp", (DL_FUNC) &_pacmapr_pacmap_optimize_cpp, 8},
    {"_pacmapr_sample_fp_pairs_nearby_cpp", (DL_FUNC) &_pacmapr_sample_fp_pairs_nearby_cpp, 5},
    {"_pacmapr_localmap_optimize_cpp", (DL_FUNC) &_pacmapr_localmap_optimize_cpp, 10},
    {"_pacmapr_pacmap_fit_optimize_cpp", (DL_FUNC) &_pacmapr_pacmap_fit_optimize_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_pacmapr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
