# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_neighbor_pairs_cpp <- function(nbrs, knn_distances, n_neighbors) {
    .Call(`_pacmapr_sample_neighbor_pairs_cpp`, nbrs, knn_distances, n_neighbors)
}

sample_mn_pairs_cpp <- function(X, n_MN, distance_kind, random_state = NULL) {
    .Call(`_pacmapr_sample_mn_pairs_cpp`, X, n_MN, distance_kind, random_state)
}

sample_fp_pairs_cpp <- function(pair_neighbors, n_points, n_neighbors, n_FP, random_state = NULL) {
    .Call(`_pacmapr_sample_fp_pairs_cpp`, pair_neighbors, n_points, n_neighbors, n_FP, random_state)
}

pacmap_optimize_cpp <- function(Y_init, pair_nb, pair_MN, pair_FP, lr, num_iters, n_threads, verbose) {
    .Call(`_pacmapr_pacmap_optimize_cpp`, Y_init, pair_nb, pair_MN, pair_FP, lr, num_iters, n_threads, verbose)
}

sample_fp_pairs_nearby_cpp <- function(Y, pair_neighbors, old_pair_FP, low_dist_thres, random_state = NULL) {
    .Call(`_pacmapr_sample_fp_pairs_nearby_cpp`, Y, pair_neighbors, old_pair_FP, low_dist_thres, random_state)
}

localmap_optimize_cpp <- function(Y_init, pair_nb, pair_MN, pair_FP, lr, num_iters, low_dist_thres, n_threads, random_state, verbose) {
    .Call(`_pacmapr_localmap_optimize_cpp`, Y_init, pair_nb, pair_MN, pair_FP, lr, num_iters, low_dist_thres, n_threads, random_state, verbose)
}

pacmap_fit_optimize_cpp <- function(Y_init, pair_XP, n_basis, lr, num_iters, n_threads, verbose) {
    .Call(`_pacmapr_pacmap_fit_optimize_cpp`, Y_init, pair_XP, n_basis, lr, num_iters, n_threads, verbose)
}

